[plugin]
repository = "https://github.com/wozaiha/umbra.git"
commit = "8eebfc98c9da1ed5057def05b1ba25cc0d4452d1"
owners = ["haroldiedema"]
project_path = "Umbra"
changelog = """
# Umbra 2.3.10

## Fixes & Improvements

- 修复老主顾（可想而知7.15还得炸）
Join [Umbra's Discord server](https://discord.gg/xaEnsuAhmm) for the latest updates and information.
Visit the [website](https://una-xiv.github.io/umbra-docs/) for more information and guides on how to make the most out of Umbra.
"""
