[plugin]
repository = "https://github.com/MeowZWR/ChatTwo.git"
commit = "30a2a1d1681e34813be8009dd7fb0918f3dfa186"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
