[plugin]
repository = "https://github.com/MeowZWR/ChatTwo.git"
commit = "cdb5b596fe2e47733eee0761a4b20002fb1150ab"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
