[plugin]
repository = "https://github.com/MeowZWR/ChatTwo.git"
commit = "03c9c751b8cae85ff4892c67fb22e337641cd154"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
