[plugin]
repository = "https://github.com/MeowZWR/ChatTwo.git"
commit = "6581f883956aab915fe2d00f3846737f00037312"
owners = [
    "Infiziert90",
    "lojewalo",
    "MeowZWR"
]
project_path = "ChatTwo"
