[plugin]
repository = "https://github.com/wozaiha/ChatBubbles.git"
commit = "2fe66feba8ab175d6efdbbe041113e2b41b4927c"
owners = ["Haplo064", "MKhayle"]
project_path = "ChatBubbles"
changelog = """### 2.1.7.2
-# API11 update for patch 7.1
-# Sent the code to Square Enix for vanilla chat bubbles in patch 7.2"""
