[plugin]
repository = "https://github.com/MeowZWR/Browsingway.git"
commit = "b3fb70e3947126b1c65e83c4b290b15f2ac48cec"
owners = ["Styr1x", "MeowZWR"]
project_path = "Browsingway"
changelog = """\
- 找runtime
- 汉化
- 鼠标悬停显示
"""
