[plugin]
repository = "https://github.com/Loskh/EurekaHelper.git"
commit = "ab9b7103abf437aa535bc19d5caf599d67d8595e"
owners = ["snorux", "KangasZ"]
project_path = "EurekaHelper"
changelog = """
- Allows switching to use chat sound effects
"""
