[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "d3cf951734ae6e30dbb430a78e1b84aed3c9ecb4"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update API XII"
