[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "14b4e4b74ecefbfa476c6d1068dc498b8d782e36"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update API XIII"
