[plugin]
repository = 'https://github.com/LittleNightmare/remote-party-finder.git'
commit = 'ebb667e1b3cf939e7ad993fe3b088926f686315a'
owners = [ 'LittleNightmare' ]
project_path = 'csharp/RemotePartyFinder'
changelog = 'update for api 12'
