[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "504b8960900c65ca4647c56781af29c79a045d2e"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """\
- 增加针对国服的跨数据中心支持\
- 汉化\
"""
