[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "edda3d0815aebac703515e07744f8f90a3c3cdfe"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """\
- 增加针对国服的跨数据中心支持\
- 汉化\
"""
