[plugin]
repository = "https://github.com/ottercorp/MarketBoardPlugin.git"
commit = "672ec555402bf3eeb4bca5558269e73d4ac2e91d"
owners = ["fmauNeko", "Yarukon"]
project_path = "MarketBoardPlugin"
changelog = """\
- 增加针对国服的跨数据中心和服务器支持\
- 汉化\
"""
